name: pushing tag version for release

on:
  push:
    branches:
      - main

    tags:
      - v*

jobs:
  check_tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo ${{github.ref}}
  build:
    if: contains(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Versions
        uses:  actions/github-script@v4
        id: set_version
        with:
          script: |
            const tag = ${GITHUB_REF##*/}
            const no_v = tag.replace('v', '')
            core.setOutput('tag', tag)
            core.setOutput('no_v', no_v)
            echo no_v
