name: pushing tag version for release

on:
  push:
    branches:
      - main

    tags:
      - v*

jobs:
  check_tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo ${{github.ref}}
  build:
    if: contains(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - id: get_version
        uses: battila7/get-version-action@v2
      
      - name: set RELEASE_VERSION
        run: echo "RELEASE_VERSION=${{ steps.get_version.outputs.version-without-v }}" >> $GITHUB_ENV

      - name: Build solution and generate NuGet package
        run: |  
          cd dotnet-img-proxy
          dotnet clean
          dotnet build -c Release
          dotnet pack -p:Version:$RELEASE_VERSION -c Release -o out

