name: pushing tag version for release

on:
  push:
    branches:
      - main

    tags:
      - v*

jobs:
  check_tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo ${{github.ref}}
  build:
    if: contains(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build solution and generate NuGet package
        run: |  
          cd dotnet-img-proxy
          dotnet clean
          dotnet build -c Release
          dotnet pack -c Release -o out
          echo ${GITHUB_REF##*/}

      - name: Push generated package
        run: dotnet nuget push /home/runner/work/dotnet-img-proxy/dotnet-img-proxy/dotnet-img-proxy/out/*.nupkg -s https://api.nuget.org/v3/index.json --skip-duplicate --no-symbols true
