name: pushing tag version for release

on:
  push:
    branches:
      - main
    pull_request:
      types: [closed]
      branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      if: "!contains(github.event.head_commit.message, 'v.')"
        - name: Run a one-line script
          run: echo "new version"
